### PR TITLE
fix: stencila UI node execution details make collapsable and improve styling

### LINKED ISSUE #2124: fix(`<stencila-ui-node-execution-details>`): make collapsable and improve styling
## Background

The `<stencila-ui-node-execution-details>` component is a container for some of the properties of node types derived from [`Executable`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/flow/executable.md). It appears at the top of executable node types. e.g. for `CodeChunk`

image

There is a preliminary implementation of this component:

https://github.com/stencila/stencila/blob/bbe35ecb008cb630c0f7249eb70d09fee7badb34/web/src/ui/nodes/properties/execution-details.ts#L51-L68

Which adds some properties that were not included in the designs (I suspect unintentionally) and excludes some (e.g. dependencies) because we do not have a re-implementation of those.

This preliminary rendering looks like this for unexecuted code chunks:

image

and like this when executed:

image

## Tasks

- [x] Make these details collapsible so that the user can hide them if they wish
- [x] Make the layout more vertically compact
- [x] Improve tooltip placement

@simonwinter could you work on this please, possibly incorporating your work-in-progress around this, and submit as a PR. You might have to work on the child elements e.g. `<stencila-ui-node-execution-ended>` to achieve designed look  but be aware that there will be other issues to improve some of those.

### PR DESCRIPTION
**Pull request by simonwinter**
**Details**

This PR resolves issue #2124, namely:

- Moves the execution details of `code-chunk`s & `code-expression`s (and any node who wishes to use it, to a collapsible panel.
- Fixes layout of node header
- Reduces vertical spacing in the execution details
- Fixes tooltip positioning

_**Notes**_

There are a few things from this that need to be looked at (not issues ... just yet):

- The collapsible component is only handling styles for basic layout - it should not apply any css layout where possible
- We need the ability to specify a "separator" border between the node card header & first collabsible element. This should be part of the #2126 ... we need to look at what design tokens should be made available pre node type.
- Need to implement the new font
- Need to review sizes of the icons in the list of execution details - not rendering well at the moment (I suspect som sub-pixel re-sampling).

---

closes #2124

### CODE REVIEW

File: web/src/ui/nodes/properties/execution-details.ts [hunk 1]
```diff
@@ -48,21 +49,33 @@ export class UINodeExecutionDetails extends LitElement {
...
-      <stencila-ui-node-execution-count
-        value=${this.count}
-      ></stencila-ui-node-execution-count>
-      <stencila-ui-node-execution-ended
-        value=${this.ended}
-      ></stencila-ui-node-execution-ended>
-      <stencila-ui-node-execution-duration
-        value=${this.duration}
-      ></stencila-ui-node-execution-duration>
+      <stencila-collapsible-node-field
```
Comment (nokome) [inline web/src/ui/nodes/properties/execution-details.ts:57]: Just noting that for consistency I renamed this to `stencila-ui-node-collapsible-property` in another PR, so there might have to be a renaming after that is merged in.

**Review by nokome — CHANGES_REQUESTED** [review]
Thanks Simon. Looks good, just some minor changes please.
